// Code generated by go generate; DO NOT EDIT!

package registry

import (
	"github.com/a-peyrard/godi"
	"github.com/a-peyrard/godi/playground/app/hello"
)

func (Registry) Register(resolver *godi.Resolver) {
	resolver.MustRegister(
		hello.NewHelloRunner,
		godi.Named("hello.runner"),
	)
	resolver.MustRegister(
		hello.NewDecorateHelloRunner,
		godi.Named("hello.runner"),
		godi.Priority(100),
		godi.Dependencies(
			godi.Inject.Auto(),
		),
	)
}
