// Code generated by go generate; DO NOT EDIT!

package registry

import (
	"github.com/a-peyrard/godi"
	"github.com/a-peyrard/godi/config"
	"github.com/a-peyrard/godi/playground/app/hello"
	aconfig "github.com/a-peyrard/godi/playground/app/config"
)

func (Registry) Register(resolver *godi.Resolver) {
	resolver.MustRegister(
		hello.NewHelloRunner,
		godi.Named("hello.runner"),
		godi.Dependencies(
			godi.Inject.Named("Config.Foobar.Foo"),
		),
	)
	resolver.MustRegister(
		hello.OnlyDevRunner,
		godi.Named("hello.runner"),
		godi.Priority(100),
		godi.When("APP_ENV").Equals("dev"),
	)
	resolver.MustRegister(
		godi.ToStaticProvider("PG"),
		godi.Named("EnvPrefix4Config"),
	)
	resolver.MustRegister(
		func(envPrefix string) (*aconfig.Config, error) {
			return config.Load[aconfig.Config](config.WithEnvPrefix(envPrefix))
		},
		godi.Named("Config"),
		godi.Dependencies(
			godi.Inject.Named("EnvPrefix4Config"),
		),
	)
	resolver.MustRegister(&godi.ConfigDynamicProvider[aconfig.Config]{})
}
